# Generated by Django 3.2.18 on 2023-02-25 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swordfighter',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='swordfighter_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
