# Generated by Django 3.2.18 on 2023-02-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_swordfighter_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='swordfighter',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending Approval'), (1, 'Published'), (2, 'Published with edit'), (3, 'Disapproved')], default=0),
        ),
    ]
