# Generated by Django 3.2.18 on 2023-03-03 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_swordfighter_suggested_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.CharField(max_length=100)),
                ('submitted_on_date', models.DateTimeField(auto_now_add=True)),
                ('reported', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('swordfighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ranking.swordfighter')),
            ],
            options={
                'ordering': ['submitted_on_date'],
            },
        ),
    ]
