# Generated by Django 3.2.18 on 2023-03-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_auto_20230303_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swordfighter',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
