# Generated by Django 3.2.18 on 2023-03-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0007_alter_swordfighter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='num_flags',
            field=models.IntegerField(default=0),
        ),
    ]
